Repository INSOPT-CDS-YES24/YES24-Android, pull requests merged in 2022-11, with the labels that each got.

#6 [Feature/UI/#3 ] Detail Activity Composition
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/subeenie/yes24_android/application/Application.kt
  app/src/main/java/com/subeenie/yes24_android/detail/DetailActivity.kt
  app/src/main/java/com/subeenie/yes24_android/detail/adapter/CastAdapter.kt
  app/src/main/java/com/subeenie/yes24_android/detail/data/CastData.kt
  app/src/main/java/com/subeenie/yes24_android/detail/util/BindingConversion.kt
  app/src/main/java/com/subeenie/yes24_android/detail/util/PriceRank.kt
  app/src/main/java/com/subeenie/yes24_android/detail/viewmodel/DetailViewModel.kt
  app/src/main/res/drawable/ic_arrow_big_left.xml
  app/src/main/res/drawable/ic_arrow_left_white.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_collapse.xml
  app/src/main/res/drawable/ic_date.xml
  app/src/main/res/drawable/ic_expand.xml
  app/src/main/res/drawable/ic_favor_off.xml
  app/src/main/res/drawable/ic_favor_on.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/drawable/img_cast1.png
  app/src/main/res/drawable/img_cast2.png
  app/src/main/res/drawable/img_cast3.png
  app/src/main/res/drawable/img_cast4.png
  app/src/main/res/drawable/img_cast5.png
  app/src/main/res/drawable/img_detail.png
  app/src/main/res/drawable/img_poster.png
  app/src/main/res/drawable/img_title.png
  app/src/main/res/drawable/selector_favor_toggle.xml
  app/src/main/res/drawable/shape_rectangle_blue.xml
  app/src/main/res/drawable/shape_rectangle_grey_5.xml
  app/src/main/res/drawable/shape_rectangle_purple.xml
  app/src/main/res/drawable/shape_rectangle_red.xml
  app/src/main/res/drawable/shape_rectangle_white_5.xml
  app/src/main/res/drawable/shape_rectangle_yellow.xml
  app/src/main/res/drawable/shpae_rectangle_blue_5.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/include_grey_divider.xml
  app/src/main/res/layout/include_price_info.xml
  app/src/main/res/layout/item_cast.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, 준우, ui

#8 [Feature/UI/#7] Server Connection / Databinding with Server / BottomNavigation Design
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/subeenie/yes24_android/application/ApiFactory.kt
  app/src/main/java/com/subeenie/yes24_android/application/Constant.kt
  app/src/main/java/com/subeenie/yes24_android/application/Yes24Service.kt
  app/src/main/java/com/subeenie/yes24_android/data/ContentDetailDto.kt
  app/src/main/java/com/subeenie/yes24_android/detail/DetailActivity.kt
  app/src/main/java/com/subeenie/yes24_android/detail/adapter/CastAdapter.kt
  app/src/main/java/com/subeenie/yes24_android/detail/util/ActorInfo.kt
  app/src/main/java/com/subeenie/yes24_android/detail/util/BindingConversion.kt
  app/src/main/java/com/subeenie/yes24_android/detail/viewmodel/DetailViewModel.kt
  app/src/main/res/drawable/ic_category.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_myticket.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/selector_bottom_navigation.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/include_price_info.xml
  app/src/main/res/layout/item_cast.xml
  app/src/main/res/menu/menu_bottom_nav.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: feature, 준우, ui

#10 [Feature/#9] myTicket page , searchView 구현
  app/src/main/java/com/subeenie/yes24_android/presentation/search/SearchFragment.kt
  app/src/main/res/drawable/ic_arrow_left_black.xml
  app/src/main/res/drawable/ic_down.xml
  app/src/main/res/drawable/ic_five.xml
  app/src/main/res/drawable/ic_four.xml
  app/src/main/res/drawable/ic_new.xml
  app/src/main/res/drawable/ic_one.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_three.xml
  app/src/main/res/drawable/ic_two.xml
  app/src/main/res/drawable/ic_up_2.xml
  app/src/main/res/drawable/ic_up_3.xml
  app/src/main/res/drawable/shape_rectangle_grey_21.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/colors.xml
Labels: feature, 수빈, ui

#14 [Feature/#13] My ticket Server
  app/build.gradle
  app/src/main/java/com/subeenie/yes24_android/MainActivity.kt
  app/src/main/java/com/subeenie/yes24_android/application/Yes24Service.kt
  app/src/main/java/com/subeenie/yes24_android/data/LikeContentsDto.kt
  app/src/main/java/com/subeenie/yes24_android/data/MyTicketDto.kt
  app/src/main/java/com/subeenie/yes24_android/presentation/mypage/MyTicketAdapter.kt
  app/src/main/java/com/subeenie/yes24_android/presentation/mypage/MyticketFragment.kt
  app/src/main/res/drawable/img.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_myticket.xml
  app/src/main/res/layout/item_my_performance_list.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, refactor, 수빈

#17 [Feature/#15] BottonNavigation Graph Apply
  app/build.gradle
  app/src/main/java/com/subeenie/yes24_android/MainActivity.kt
  app/src/main/java/com/subeenie/yes24_android/presentation/detail/DetailActivity.kt
  app/src/main/java/com/subeenie/yes24_android/presentation/detail/data/CastData.kt
  app/src/main/java/com/subeenie/yes24_android/presentation/detail/util/BindingConversion.kt
  app/src/main/java/com/subeenie/yes24_android/presentation/home/HomeFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/bottom_navigation_graph.xml
Labels: feature, 준우

#18 [Feature/#16] Home Fragment 서버 연결, 데이터 수정 완료!
  app/src/main/java/com/subeenie/yes24_android/application/Yes24Service.kt
  app/src/main/java/com/subeenie/yes24_android/data/HomeContentsDTO.kt
  app/src/main/java/com/subeenie/yes24_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/subeenie/yes24_android/presentation/home/HomePreferRvAdapter.kt
  app/src/main/java/com/subeenie/yes24_android/presentation/home/HomePreferRvData.kt
  app/src/main/java/com/subeenie/yes24_android/presentation/home/HomeSimilarRvApater.kt
  app/src/main/java/com/subeenie/yes24_android/presentation/home/HomeSimilarRvData.kt
  app/src/main/res/drawable/default_dot.xml
  app/src/main/res/drawable/dot_indicator.xml
  app/src/main/res/drawable/selected_dot.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/HomePreferRVData.xml
Labels: feature, 강희
